version: "3.8"

services:
  go:
    image: praktikum:1.0.0
    build: 
      context: .
    container_name: praktikum
    ports:
      - "8000:8000"
    depends_on:
      - "db"

  db:
    image:  mysql:8.0 
    container_name:  my-mysql-container 
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: 
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: crud_go 
      MYSQL_TCP_PORT: 3306
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  my-db: