name: Deployment-to-server
on: 
  push: 
    branches: main

jobs:
  build-docker: 
    name: Build and Push Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker
        run: docker build -t fildzaanf/praktikum-aws:1.0.0 .
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker push
        run: docker push fildzaanf/praktikum-aws:1.0.0 

  build:
    name: Deploy-to-server
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
    - name: pull-test-deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker pull fildzaanf/praktikum-aws:1.0.0 
          docker stop praktikum-aws || true
          docker rm praktikum-aws || true
          docker run -d -p 8080:8080 --name praktikum-aws fildzaanf/praktikum-aws:1.0.0 