name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port:  ${{ secrets.PORT }}
          script: |
            export PATH=$PATH:/usr/local/go/bin
            cd project
            git pull origin main
            sudo docker compose -f docker-compose.yml up -d --build